
title: Lyrid
email: deveshdanai@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Lyrid is blog about Front-end web development 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  deveshdanai

# Build settings
theme: minima
plugins:
  - jekyll-feed
